#!/usr/bin/env bash
#
# MediaStack-RAD v2 installer.
#
# This script sets up RAD on a fresh Linux host. It:
#   1. Checks prerequisites (docker, compose plugin, curl)
#   2. Creates the stack directory with correct ownership
#   3. Creates the shared Docker network
#   4. Writes a sensible docker-compose.yml for RAD
#   5. Pulls and starts RAD
#   6. Prints the URL to open
#
# Idempotent — rerun it any time to verify state, upgrade, or recover.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/nnyan/mediastack-rad-v2/main/install.sh | bash
#
# Or with custom paths:
#   STACK_DIR=/opt/mediacenter bash install.sh

set -euo pipefail

# ---- Configurable variables ------------------------------------------------

STACK_DIR="${STACK_DIR:-/home/stack/mediacenter}"
RAD_IMAGE="${RAD_IMAGE:-ghcr.io/nnyan/mediastack-rad-v2:latest}"
RAD_PORT="${RAD_PORT:-8090}"
RAD_DIR="${RAD_DIR:-/home/stack/msrad}"
NETWORK_NAME="${NETWORK_NAME:-mediastack}"

# ---- Output helpers --------------------------------------------------------

# Use plain ASCII markers when NO_COLOR is set or stdout is not a TTY.
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
    GREEN=$'\033[32m'; RED=$'\033[31m'; YELLOW=$'\033[33m'; BOLD=$'\033[1m'; DIM=$'\033[2m'; RESET=$'\033[0m'
else
    GREEN=""; RED=""; YELLOW=""; BOLD=""; DIM=""; RESET=""
fi

ok()   { echo "${GREEN}[ok]${RESET}   $*"; }
info() { echo "${BOLD}[info]${RESET} $*"; }
warn() { echo "${YELLOW}[warn]${RESET} $*"; }
fail() { echo "${RED}[fail]${RESET} $*" >&2; exit 1; }
step() { echo; echo "${BOLD}==>${RESET} $*"; }

# ---- Prerequisite checks ---------------------------------------------------

step "Checking prerequisites"

if ! command -v docker >/dev/null 2>&1; then
    fail "Docker is not installed. See https://docs.docker.com/engine/install/"
fi
ok "docker: $(docker --version)"

if ! docker compose version >/dev/null 2>&1; then
    fail "Docker Compose v2 plugin is missing. Install docker-compose-plugin."
fi
ok "docker compose: $(docker compose version --short)"

if ! docker info >/dev/null 2>&1; then
    fail "Cannot talk to the Docker daemon. Are you in the 'docker' group,
      or running with sudo?"
fi

# Check we have a reasonably recent Docker API version. Very old clients
# (like those bundled with buster) can't talk to Traefik.
API_VERSION=$(docker version --format '{{.Server.APIVersion}}' 2>/dev/null || echo "unknown")
ok "docker API: $API_VERSION"

# ---- Directories -----------------------------------------------------------

step "Creating directories"

mkdir -p "$STACK_DIR"
mkdir -p "$STACK_DIR/config"
mkdir -p "$STACK_DIR/config/traefik"
mkdir -p "$STACK_DIR/config/traefik/letsencrypt"
mkdir -p "$RAD_DIR"

# Make acme.json exist with correct mode so Traefik doesn't complain on
# first start — generator.py will also do this, but belt and braces.
touch "$STACK_DIR/config/traefik/letsencrypt/acme.json"
chmod 600 "$STACK_DIR/config/traefik/letsencrypt/acme.json"

ok "stack dir: $STACK_DIR"
ok "RAD dir:   $RAD_DIR"

# ---- Network ---------------------------------------------------------------

step "Creating Docker network '$NETWORK_NAME'"

if docker network inspect "$NETWORK_NAME" >/dev/null 2>&1; then
    ok "network already exists"
else
    docker network create "$NETWORK_NAME" >/dev/null
    ok "network created"
fi

# ---- RAD compose file ------------------------------------------------------

step "Writing RAD docker-compose.yml"

cat > "$RAD_DIR/docker-compose.yml" <<EOF
# Auto-generated by MediaStack-RAD installer. Edit freely.
services:
  mediastack-rad:
    image: $RAD_IMAGE
    container_name: mediastack-rad
    restart: unless-stopped
    ports:
      - "$RAD_PORT:8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $STACK_DIR:/compose
    environment:
      RAD_STACK_DIR: /compose
      RAD_TRAEFIK_DIR: /compose/config/traefik
    networks:
      - $NETWORK_NAME

networks:
  $NETWORK_NAME:
    name: $NETWORK_NAME
    external: true
EOF

ok "wrote $RAD_DIR/docker-compose.yml"

# ---- Pull + start ----------------------------------------------------------

step "Pulling RAD image"
docker pull "$RAD_IMAGE"

step "Starting RAD"
docker compose -f "$RAD_DIR/docker-compose.yml" up -d

# Give it a moment to boot before probing.
sleep 3

# ---- Post-install health check ---------------------------------------------

step "Verifying install"

for i in 1 2 3 4 5 6 7 8 9 10; do
    if curl -fsS "http://localhost:$RAD_PORT/api/version" >/dev/null 2>&1; then
        VERSION=$(curl -s "http://localhost:$RAD_PORT/api/version" | \
                  grep -oE '"version":"[^"]+"' | cut -d'"' -f4)
        ok "RAD is responding. Version: $VERSION"
        break
    fi
    if [ "$i" = 10 ]; then
        warn "RAD didn't respond after 10 attempts. Check logs with:"
        warn "  docker logs mediastack-rad"
        exit 1
    fi
    sleep 2
done

# ---- Done ------------------------------------------------------------------

HOST_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "your-host-ip")

cat <<EOF

${GREEN}${BOLD}Installation complete.${RESET}

Open the dashboard:
  ${BOLD}http://$HOST_IP:$RAD_PORT${RESET}

Next steps (in this order):
  1. Go to ${BOLD}Stack Builder${RESET} and pick your services.
  2. Fill in your domain and Cloudflare API token.
  3. Click ${BOLD}Deploy Stack${RESET}.
  4. Visit ${BOLD}Checklist${RESET} for what to configure after.
  5. Watch ${BOLD}Health${RESET} for any issues.

Stack directory: ${DIM}$STACK_DIR${RESET}
RAD directory:   ${DIM}$RAD_DIR${RESET}

To upgrade RAD later, rerun this script.
EOF
